export const ADD_NOTE = 'ADD_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

export const START_EDITING_NOTE = 'START_EDITING_NOTE';
export const CANCEL_EDITING_NOTE = 'CANCEL_EDITING_NOTE';

export const ADD_NOTE_FOCUS = 'ADD_NOTE_FOCUS';
export const ADD_NOTE_BLUR = 'ADD_NOTE_BLUR';
export const ADD_NOTE_TEXT_CHANGE = 'ADD_NOTE_TEXT_CHANGE';

export const START_LOADING_NOTES = 'START_LOADING_NOTES';
export const LOADING_NOTES_FAILURE = 'LOADING_NOTES_FAILURE';
export const LOADING_NOTES_SUCCESS = 'LOADING_NOTES_SUCCESS';

export const START_SENDING_NOTE_TO_SERVER = 'START_SENDING_NOTE_TO_SERVER';
export const SENDING_NOTE_TO_SERVER_FAILURE = 'SENDING_NOTE_TO_SERVER_FAILURE';
export const SENDING_NOTE_TO_SERVER_SUCCESS = 'SENDING_NOTE_TO_SERVER_SUCCESS';

export const START_DELETING_NOTE_FROM_SERVER = 'START_DELETING_NOTE_FROM_SERVER';
export const DELETING_NOTE_FROM_SERVER_FAILURE = 'DELETING_NOTE_FROM_SERVER_FAILURE';
export const DELETING_NOTE_FROM_SERVER_SUCCESS = 'DELETING_NOTE_FROM_SERVER_SUCCESS';
