export const ADD_NOTE = 'ADD_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

export const START_EDITING_NOTE = 'START_EDITING_NOTE';
export const CANCEL_EDITING_NOTE = 'CANCEL_EDITING_NOTE';

export const START_ADDING_NOTE = 'START_ADDING_NOTE';
export const STOP_ADDING_NOTE = 'STOP_ADDING_NOTE';
