export const ADD_NEW_NOTE = 'ADD_NEW_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

export const START_EDITING_NOTE = 'START_EDITING_NOTE';
export const CANCEL_EDITING_NOTE = 'CANCEL_EDITING_NOTE';

export const START_TOUCH_ADD_LIST_MEMBER_INPUT = 'START_TOUCH_ADD_LIST_MEMBER_INPUT';
export const STOP_TOUCH_ADD_LIST_MEMBER_INPUT = 'STOP_TOUCH_ADD_LIST_MEMBER_INPUT';
