export const ADD_NOTE = 'ADD_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

export const START_EDITING_NOTE = 'START_EDITING_NOTE';
export const CANCEL_EDITING_NOTE = 'CANCEL_EDITING_NOTE';

export const ADD_NOTE_FOCUS = 'ADD_NOTE_FOCUS';
export const ADD_NOTE_BLUR = 'ADD_NOTE_BLUR';
export const ADD_NOTE_TEXT_CHANGE = 'ADD_NOTE_TEXT_CHANGE';
